# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
loom.mixin.useLegacyMixinAp=false
loom.platform=neoforge
kotlin.compiler.execution.strategy=in-process

# Minecraft / loader
minecraft_version=1.21.1
neo_forge_version=21.1.111
architectury_version=13.0.8
forge_kotlin_version=5.11.0

# Mod Properties
mod_version=0.4.0
maven_group=org.robbie
archives_base_name=yaha

# Dependencies
cloth_config_version=15.0.130
hexcasting_version=0.12.0-devel-pre-39
inline_version=1.2.2
patchouli_version=1.21.1-92-NEOFORGE
paucal_version=0.7.1-pre-27
caelus_version=7.0.1+1.21.1
mixinextras_version=0.5.0
serialization_hooks_version=0.4.99999
